### PR TITLE
fix: confirm modal breaks cursor

### LINKED ISSUE #49: Bug When remove Timers Unable to type
Sometimes when I remove timers, the mouse is left unable to type, until I open the browser and it is fixed.

https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/52177646/967097da-1307-4be3-ae54-a9b073729abb

### PR DESCRIPTION
**Pull request by jacobtread**
## Description

Fixes some weird behavior with the native confirm dialog that prevents the obsidian editor from working after one is shown (Unless you click another window then click back)

## Changes

- Adds an obsidian modal for confirmations
- Replaces usage of confirm with the custom modal

## Related issues
- Closes #49

### CODE REVIEW

File: src/confirm-modal.ts [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+					this.picked = true;
+					this.close();
+					this.callback(false);
+				})
+			);
+	}
+
+	onClose(): void {
+		if (!this.picked) {
+			console.log("Fallback");
```
Comment (Ellpeck) [inline src/confirm-modal.ts:49]: Please remove this debug print :)

File: src/confirm-modal.ts [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+	// Message to show in the modal
+	message: string;
+
+	// Callback to run on user choice
+	callback: (choice: boolean) => void;
+
+	// Whether an option was picked
+	picked: boolean;
+
+	constructor(
```
Comment (Ellpeck) [inline src/confirm-modal.ts:13]: Would you mind making the constructor head one line? It's not really big enough to warrant the waste of vertical space imo

**Review by Ellpeck — CHANGES_REQUESTED** [review]
Hi, thanks so much for this contribution!! 

Other than a few tiny nitpicks, it looks really good :)

**Comment by jacobtread** [comment]
My bad, the formatting is from prettier because I use that for my plugin and the log is something I forgot to remove haha, brought the fix straight over from my plugin

**Review by Ellpeck — APPROVED** [review]
